### ISSUE TITLE
userRoles() throws error

### ISSUE THREAD

**Issue by sherin-mathew** [adnanesaghir/acl-elasticsearch-backend#3]
@adnanesaghir 
addUserRoles() method is not adding any roles to ES and when I tried to fetch the user roles using userRoles() method, it throws the below exception.

```
body:"{"query":{"filtered":{"filter":{"bool":{"should":[{"term":{"key":"Joe"}}]}}}}}"
displayName:"BadRequest"
isOperational:true
message:"[parsing_exception] no [query] registered for [filtered], with { line=1 & col=22 }"
```

I think this module is not supporting higher versions of elastic search.
My elasticsearch version is 6.0

**Comment by adnanesaghir** [comment]
Hi sherin-mathew, sorry this module supports first version of elasticsearch only.
Feel free to contribute ;)
